apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-roms
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /NFS
    server: 192.168.122.167
